name: movie_app
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.5.0


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  json_annotation: ^4.9.0
  equatable: ^2.0.5
  injectable: ^2.4.4
  flutter_bloc: ^8.1.6
  rxdart: ^0.28.0
  go_router: ^14.2.3
  flutter_localization: ^0.2.1
  intl: ^0.19.0
  dio: ^5.6.0
  logger: ^2.4.0
  get_it: ^7.7.0
  flutter_dotenv: ^5.1.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter  
  flutter_lints: ^4.0.0
  build_runner: ^2.4.12
  json_serializable: ^6.8.0
  injectable_generator: ^2.6.2


flutter:

  
  uses-material-design: true

  assets:
    - assets/images/
    - .env

fonts:
    - family: Gilroy
      fonts:
        - asset: assets/fonts/gilroy/Gilroy-Light.ttf
          weight: 300
        - asset: assets/fonts/gilroy/Gilroy-Regular.ttf
          weight: 400
        - asset: assets/fonts/gilroy/Gilroy-Medium.ttf
          weight: 500
        - asset: assets/fonts/gilroy/Gilroy-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/gilroy/Gilroy-Bold.ttf
          weight: 700
    - family: Gilroy-Light
      fonts:
        - asset: assets/fonts/gilroy/Gilroy-Light.ttf
    - family: Gilroy-Regular
      fonts:
        - asset: assets/fonts/gilroy/Gilroy-Regular.ttf
    - family: Gilroy-Medium
      fonts:
        - asset: assets/fonts/gilroy/Gilroy-Medium.ttf
    - family: Gilroy-SemiBold
      fonts:
        - asset: assets/fonts/gilroy/Gilroy-SemiBold.ttf
    - family: Gilroy-Bold
      fonts:
        - asset: assets/fonts/gilroy/Gilroy-Bold.ttf


